name = "carshow-api"
main = "src/index.ts"
compatibility_date = "2026-02-09"
account_id = "efdb9bf05190f003e42285057bfeca6f"

[vars]
PUBLIC_SITE_URL = "https://rallyattheridge.org/"

[[d1_databases]]
binding = "DB"
database_name = "carshow_db"
database_id = "971e959c-a7f6-45a4-bfd3-289fbbd10db7"
